# Generated by Django 4.0.2 on 2022-06-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='images',
            fields=[
                ('img_id', models.AutoField(primary_key=True, serialize=False)),
                ('img_name', models.CharField(max_length=50)),
                ('image', models.ImageField(default='', upload_to='image/images')),
            ],
        ),
    ]
